// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              0
// Endpoints:                           20
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    seal_presale_multiversx
    (
        init => init
        contribute => contribute
        startPresale => start_presale
        pausePresale => pause_presale
        endPresale => end_presale
        updateTreasury => update_treasury
        setWhitelistEnabled => set_whitelist_enabled
        addToWhitelist => add_to_whitelist
        removeFromWhitelist => remove_from_whitelist
        updatePricePerSeal => update_price_per_seal
        updatePurchaseLimits => update_purchase_limits
        updateRaiseCap => update_raise_cap
        withdrawRemainingTokens => withdraw_remaining_tokens
        emergencyWithdrawEgld => emergency_withdraw_egld
        getPresaleStats => get_presale_stats
        getContributor => get_contributor_info
        isWhitelisted => is_whitelisted
        calculateTokensForContribution => calculate_tokens_for_contribution
        getTimeRemaining => get_time_remaining
    )
}
