"use client";

import React, { useState, useEffect } from "react";
import { X, Zap } from "lucide-react";

interface UIComponent {
  id: string;
  type: string;
  config: any;
  timestamp: number;
}

interface GenerativeUIProps {
  components: UIComponent[];
  onClose: (id: string) => void;
}

export function GenerativeUI({ components, onClose }: GenerativeUIProps) {
  return (
    <>
      {components.map((component) => (
        <GeneratedComponent
          key={component.id}
          component={component}
          onClose={() => onClose(component.id)}
        />
      ))}
    </>
  );
}

function GeneratedComponent({ component, onClose }: { component: UIComponent; onClose: () => void }) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    // Animate in
    setTimeout(() => setIsVisible(true), 10);
  }, []);

  const renderComponent = () => {
    switch (component.type) {
      case "swap_card":
        return (
          <SwapCard
            tokens={component.config.tokens || ["SOL", "USDC"]}
            amount={component.config.amount || 0}
          />
        );
      case "dashboard":
        // Old dashboard component removed - no longer supported
        return null;
      case "wallet_balance":
        return <WalletBalanceCard />;
      case "transaction_builder":
        return <TransactionBuilderCard config={component.config} />;
      default:
        return (
          <div className="p-6 bg-black/80 backdrop-blur-2xl border border-white/20 rounded-2xl">
            <div className="text-white">Unknown component type: {component.type}</div>
            <pre className="text-xs text-gray-400 mt-2">{JSON.stringify(component.config, null, 2)}</pre>
          </div>
        );
    }
  };

  return (
    <div
      className={`fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-30 transition-all duration-500 ${
        isVisible ? "opacity-100 scale-100" : "opacity-0 scale-95"
      }`}
    >
      <div className="relative">
        {renderComponent()}
        <button
          onClick={onClose}
          className="absolute -top-2 -right-2 p-1.5 bg-gray-800 hover:bg-gray-700 rounded-full border border-gray-600 transition-colors"
        >
          <X className="w-4 h-4 text-gray-400" />
        </button>
      </div>
    </div>
  );
}

// Example Generated Components

function SwapCard({ tokens, amount }: { tokens: string[]; amount: number }) {
  return (
    <div className="p-6 bg-black/80 backdrop-blur-2xl border border-white/20 rounded-2xl w-80 animate-in fade-in zoom-in shadow-2xl">
      <div className="flex items-center gap-2 mb-4">
        <Zap className="w-5 h-5 text-purple-400" />
        <h3 className="text-lg font-bold text-white">Swap {amount} {tokens[0]}</h3>
      </div>
      <div className="space-y-4">
        <div className="p-3 bg-gray-900/50 rounded-lg border border-gray-700">
          <div className="text-xs text-gray-400 mb-1">From</div>
          <div className="text-white font-medium">{amount} {tokens[0]}</div>
        </div>
        <div className="flex justify-center">
          <div className="p-2 bg-purple-600/20 rounded-full border border-purple-500/30">
            <svg className="w-4 h-4 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </div>
        <div className="p-3 bg-gray-900/50 rounded-lg border border-gray-700">
          <div className="text-xs text-gray-400 mb-1">To</div>
          <div className="text-white font-medium">~{amount * 150} {tokens[1]}</div>
        </div>
        <button className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white rounded-lg py-3 font-bold hover:scale-105 transition-transform">
          Confirm Transaction
        </button>
      </div>
    </div>
  );
}

// DashboardCard component removed - old AI dashboard no longer supported

function WalletBalanceCard() {
  return (
    <div className="p-6 bg-black/80 backdrop-blur-2xl border border-white/20 rounded-2xl w-80 animate-in fade-in zoom-in shadow-2xl">
      <h3 className="text-lg font-bold text-white mb-4">Wallet Balance</h3>
      <div className="space-y-3">
        <div className="p-4 bg-gradient-to-br from-purple-600/20 to-blue-600/20 rounded-lg border border-purple-500/30">
          <div className="text-xs text-gray-400 mb-1">Total Balance</div>
          <div className="text-3xl font-bold text-white">12.45 SOL</div>
          <div className="text-sm text-gray-400 mt-1">≈ $2,450.00</div>
        </div>
        <div className="text-xs text-gray-500 text-center">Generated by AI</div>
      </div>
    </div>
  );
}

function TransactionBuilderCard({ config }: { config: any }) {
  return (
    <div className="p-6 bg-black/80 backdrop-blur-2xl border border-white/20 rounded-2xl w-96 animate-in fade-in zoom-in shadow-2xl">
      <h3 className="text-lg font-bold text-white mb-4">Transaction Builder</h3>
      <div className="space-y-3">
        <div className="p-3 bg-gray-900/50 rounded-lg border border-gray-700">
          <div className="text-xs text-gray-400 mb-2">Instruction Type</div>
          <div className="text-white font-medium">{config.type || "Transfer"}</div>
        </div>
        <button className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white rounded-lg py-3 font-bold hover:scale-105 transition-transform">
          Build Transaction
        </button>
      </div>
    </div>
  );
}


